### ISSUE TITLE
翻译建议

### ISSUE THREAD

**Issue by liangminhua** [oyyd/typescript-handbook-zh#14]
基本类型 -- 数组类型
用样我们也需要索引所对应的返回值的类型。
应该 是 ‘这样’吧。
类型推断 --最佳通用类型
Ideally, we may want zoo to be inferred as an Animal[]
应该翻译成：在理想情况下，我们希望zoo 被推断为Animal[]
声明合并--用模块合并类，函数和枚举
Similarly, modules can be used to extend enums with static members
相似地，模块也可以同静态成员来扩展枚举
应该是：相似地，模块也可以用静态成员来扩展枚举

**Comment by oyyd** [comment]
:+1: 
已修复。没有看到通知，回复的太晚，非常抱歉。
